### ISSUE TITLE
Error While installing requirements.txt

### ISSUE THREAD

**Issue by INSANELYOFFICIAL** [manintel/nyaabag#1]
Got Error while installing requirements.txt.

To recreate the issue:

Step 1: git clone https://github.com/manintel/nyaabag

Step 2: python -m pip install -r requirements.txt. !

This Is the error which I got: 

```
ERROR: Command errored out with exit status 1:
   command: /data/data/com.termux/files/usr/bin/python /data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /data/data/com.termux/files/usr/tmp/tmppwsy515m
       cwd: /data/data/com.termux/files/usr/tmp/pip-install-gascds9q/pandas_a26d77d827da40cfbc5ba4f3f7b7675f
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/data/data/com.termux/files/usr/tmp/pip-build-env-21g_ltcp/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/data/data/com.termux/files/usr/tmp/pip-build-env-21g_ltcp/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/data/data/com.termux/files/usr/tmp/pip-build-env-21g_ltcp/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 258, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/data/data/com.termux/files/usr/tmp/pip-build-env-21g_ltcp/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 18, in <module>
      import numpy
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/53/05/bf382e8bc60731906a2e7261648bcea3a6b309ad2b9952010737a1b9413e/pandas-1.3.0.tar.gz#sha256=c554e6c9cf2d5ea1aba5979cc837b3649539ced0e18ece186f055450c86622e2 (from https://pypi.org/simple/pandas/) (requires-python:>=3.7.1). Command errored out with exit status 1: /data/data/com.termux/files/usr/bin/python /data/data/com.termux/files/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /data/data/com.termux/files/usr/tmp/tmppwsy515m Check the logs for full command output.
```

[Screenshot_20210908-000706.jpg](https://user-images.githubusercontent.com/24321440/132395551-f3ef5340-8c7f-485e-a97e-41844058bea0.jpg)

**Comment by daynum** [comment]
I see you re using termux?
There's a thread on termux's github addressing this problem, and many workarounds to solve try these
[https://github.com/termux/termux-packages/issues/136#issuecomment-341087794](https://github.com/termux/termux-packages/issues/136#issuecomment-347888817)  
[https://github.com/termux/termux-packages/issues/136#issuecomment-341087794](https://github.com/termux/termux-packages/issues/136#issuecomment-341087794)

**Comment by INSANELYOFFICIAL** [comment]
> I see you re using termux?
> There's a thread on termux's github addressing this problem, and many workarounds to solve try these
> [https://github.com/termux/termux-packages/issues/136#issuecomment-341087794](https://github.com/termux/termux-packages/issues/136#issuecomment-347888817)  
> [https://github.com/termux/termux-packages/issues/136#issuecomment-341087794](https://github.com/termux/termux-packages/issues/136#issuecomment-341087794)

I did that process and after that when I tried running nyaabag.py I got another error.

```
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/nyaabag/nyaabag.py", line 3, in <module>
    from fuzzywuzzy import fuzz,process
ModuleNotFoundError: No module named 'fuzzywuzzy'
```

**Comment by INSANELYOFFICIAL** [comment]
> I see you re using termux?
> There's a thread on termux's github addressing this problem, and many workarounds to solve try these
> [https://github.com/termux/termux-packages/issues/136#issuecomment-341087794](https://github.com/termux/termux-packages/issues/136#issuecomment-347888817)  
> [https://github.com/termux/termux-packages/issues/136#issuecomment-341087794](https://github.com/termux/termux-packages/issues/136#issuecomment-341087794)

Okay so it gave me an no fuzzywuzzy module found error so I ran `pip install fuzzywuzzy` and it worked.
